<script setup>
import {ref,watch,onMounted,onUnmounted} from 'vue'
import {Sparkles,Car,RefreshCw,X} from 'lucide-vue-next'
const props=defineProps({api:Function,config:Object,houses:Array,seed:Object,auth:String})
const emit=defineEmits(['acquired'])
const rows=ref([]),selected=ref(null),formOpen=ref(false),form=ref({}),photos=ref([]),photoUrls=ref([]),busy=ref(false),error=ref(''),purchase=ref(null)
const idr=v=>v==null?'—':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v)
const labels={BUY_CONDITIONAL:'Beli bersyarat',NEGOTIATE:'Nego dulu',REVIEW:'Periksa dulu',SKIP:'Lewati'}
const moneyFields=[['askPrice','Harga penawaran / bid (Rp)'],['capital','Modal maksimal per unit (Rp)'],['maxPurchase','Batas harga beli dari user (Rp)'],['targetProfit','Target laba (Rp)'],['repairLow','Servis — biaya rendah (Rp)'],['repairHigh','Servis — biaya tinggi (Rp)'],['taxCost','Pajak kendaraan / dokumen (Rp)'],['otherCosts','Transport, iklan & biaya lain (Rp)'],['riskBuffer','Cadangan risiko (Rp)'],['saleLow','Harga jual rendah (Rp)'],['saleMid','Harga jual tengah (Rp)'],['saleHigh','Harga jual tinggi (Rp)']]
const positive=['askPrice','capital','maxPurchase','saleLow','saleMid','saleHigh']
let timer,polling=false
async function perform(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function refresh(){rows.value=await props.api('/purchase-decisions')}
function reset(seed={}){form.value={vehicle:'',year:'',kilometer:'',transmission:'UNKNOWN',stnk:'UNKNOWN',bpkb:'UNKNOWN',askPrice:'',capital:65000000,maxPurchase:50000000,targetProfit:5000000,repairLow:2000000,repairHigh:5000000,taxCost:0,otherCosts:1000000,riskBuffer:2000000,saleLow:'',saleMid:'',saleHigh:'',evidenceConfirmed:false,inspectionConfirmed:false,criticalRisk:false,notes:'',marketEvidence:'',purchaseType:'DIRECT',houseId:null,sourceLotId:null,...seed};photos.value=[];formOpen.value=true;error.value=''}
watch(()=>props.seed,s=>{if(s)reset(s)},{immediate:true})
watch(()=>form.value.purchaseType,type=>{if(type==='DIRECT'){form.value.houseId=null;form.value.sourceLotId=null}else if(!form.value.houseId)form.value.houseId=props.houses.find(h=>h.active)?.id||null})
function clearUrls(){photoUrls.value.forEach(p=>URL.revokeObjectURL(p.url));photoUrls.value=[]}
async function load(id){clearUrls();selected.value=await props.api('/purchase-decisions/'+id);purchase.value=null;for(const p of selected.value.photos||[]){const r=await fetch(`/api/purchase-decisions/${id}/photos/${p.id}`,{headers:{Authorization:`Basic ${props.auth}`,'X-PhiveGarage':'web'}});if(!r.ok)throw Error('Foto gagal dimuat');photoUrls.value.push({id:p.id,url:URL.createObjectURL(await r.blob())})}}
function choosePhotos(e){photos.value=Array.from(e.target.files||[]);if(photos.value.length>6||photos.value.some(p=>p.size>3*1024*1024)){error.value='Maksimal 6 foto JPG/PNG, masing-masing 3 MB';photos.value=[];e.target.value=''}}
async function save(){await perform(async()=>{const d={...form.value};for(const k of ['year','kilometer'])d[k]=d[k]===''||d[k]==null?null:Number(d[k]);for(const [k] of moneyFields)d[k]=Number(d[k]);if(d.purchaseType==='DIRECT'){d.houseId=null;d.sourceLotId=null}const body=new FormData();body.append('input',new Blob([JSON.stringify(d)],{type:'application/json'}));for(const p of photos.value)body.append('photos',p);const out=await props.api('/purchase-decisions',{method:'POST',body});formOpen.value=false;await refresh();await load(out.id)})}
async function analyze(){await perform(async()=>{await props.api(`/purchase-decisions/${selected.value.id}/ai`,{method:'POST'});await load(selected.value.id);await refresh()})}
async function acquire(){await perform(async()=>{const out=await props.api(`/purchase-decisions/${selected.value.id}/acquire`,{method:'POST',body:JSON.stringify(purchase.value)});await load(selected.value.id);await refresh();emit('acquired',out.id)})}
onMounted(async()=>{await perform(refresh);timer=setInterval(async()=>{if(polling||busy.value||!['QUEUED','PROCESSING'].includes(selected.value?.ai_status))return;polling=true;try{const out=await props.api('/purchase-decisions/'+selected.value.id);selected.value={...selected.value,...out};if(['READY','FAILED'].includes(out.ai_status))await refresh()}catch(e){error.value=e.message}finally{polling=false}},2500)})
onUnmounted(()=>{clearInterval(timer);clearUrls()})
</script>
<template>
<div class="page-heading"><div><span class="eyebrow">BUY WITH A CLEAR LIMIT</span><h1>Keputusan beli</h1><p>Nilai unit seller langsung atau lelang: harga, nego, skenario laba, dan risiko.</p></div><div class="heading-actions"><button class="secondary" :disabled="busy" @click="perform(refresh)"><RefreshCw :size="16"/> Refresh</button><button class="primary" @click="reset()">+ Analisis unit</button></div></div>
<div v-if="error" class="error" role="alert">{{error}}</div>
<section v-if="formOpen" class="panel"><div class="section-head"><h3>Data & parameter keputusan</h3><button class="icon-button" @click="formOpen=false"><X/></button></div><form @submit.prevent="save"><div class="field-grid"><label>Nama unit<input v-model="form.vehicle" maxlength="300" required placeholder="Contoh: sedan 2.3 AT"></label><label>Tahun<input v-model.number="form.year" type="number" min="1950" max="2100"></label><label>Kilometer<input v-model.number="form.kilometer" type="number" min="0" max="100000000000"></label><label>Sumber pembelian<select v-model="form.purchaseType" :disabled="!!form.sourceLotId"><option value="DIRECT">Seller langsung</option><option value="AUCTION">Lelang</option></select></label><label v-if="form.purchaseType==='AUCTION'">Balai lelang<select v-model="form.houseId" :disabled="!!form.sourceLotId" required><option :value="null" disabled>Pilih balai</option><option v-for="h in houses.filter(h=>h.active||h.id===form.houseId)" :key="h.id" :value="h.id">{{h.name}}</option></select></label><label>Transmisi<select v-model="form.transmission"><option value="UNKNOWN">Belum diketahui</option><option value="MT">MT</option><option value="AT">AT / CVT</option></select></label><label v-for="key in ['stnk','bpkb']" :key="key">{{key.toUpperCase()}}<select v-model="form[key]"><option value="UNKNOWN">Belum diketahui</option><option value="ADA">Ada</option><option value="TIDAK_ADA">Tidak ada</option></select></label><label v-for="[key,label] in moneyFields" :key="key">{{label}}<input v-model.number="form[key]" type="number" :min="positive.includes(key)?1:0" max="100000000000" required></label></div><p>Harga jual rendah/tengah/tinggi diisi dari pembanding yang kamu temukan. Tanpa bukti harga yang diverifikasi, hasil hanya simulasi dan berstatus Periksa dulu.</p><label>Bukti / pembanding harga<textarea v-model="form.marketEvidence" maxlength="5000" rows="3" placeholder="Link, tanggal, tipe/tahun/kondisi pembanding, harga listing atau transaksi, dan alasan rentang harga."/></label><label>Kondisi, dokumen & tujuan pembelian<textarea v-model="form.notes" maxlength="5000" rows="3" placeholder="Catatan seller, kondisi yang terlihat, hasil test drive, target pembeli, dan hal yang belum diketahui."/></label><label>Foto unit — opsional<input type="file" accept="image/jpeg,image/png" multiple @change="choosePhotos"><small>Maksimal 6 JPG/PNG, 3 MB per foto. Foto tersimpan di server; dikirim ke AI hanya saat tombol analisis AI ditekan.</small></label><div class="checks"><label><input v-model="form.evidenceConfirmed" type="checkbox"> Saya sudah memverifikasi pembanding harga dan rentang jual</label><label><input v-model="form.inspectionConfirmed" type="checkbox"> Saya sudah melakukan inspeksi fisik dan verifikasi kondisi</label><label><input v-model="form.criticalRisk" type="checkbox"> Ada risiko berat / alasan untuk tidak membeli</label></div><button class="primary" :disabled="busy">Hitung & simpan keputusan</button></form></section>
<section v-if="selected" class="panel decision-report"><div class="section-head"><div><span class="eyebrow">YOUR BUYING DECISION</span><h2>{{selected.data.vehicle}}</h2><p>{{selected.data.year||'Tahun belum diisi'}} · {{selected.fee_snapshot.name}} · Harga penawaran {{idr(selected.data.askPrice)}}</p></div><span class="badge" :class="selected.results.recommendation==='SKIP'?'SKIP':selected.results.recommendation==='BUY_CONDITIONAL'?'BID':'REVIEW'">{{labels[selected.results.recommendation]}}</span></div><div class="info-note">{{selected.results.recommendation==='BUY_CONDITIONAL'?'Beli bersyarat: hitungan memenuhi parameter, tetap pastikan hasil inspeksi dan transaksi.':'Lihat alasan, batas harga, dan data yang belum terverifikasi sebelum mengambil keputusan.'}}</div><ul><li v-for="r in selected.results.reasons" :key="r">{{r}}</li></ul><div class="stats"><article><span>Batas beli konservatif</span><strong>{{idr(selected.results.maxPurchase)}}</strong><small>Bersyarat pada input harga & biaya</small></article><article><span>Rentang buka nego</span><strong>{{idr(selected.results.negotiationLow)}}</strong><small>sampai {{idr(selected.results.negotiationHigh)}} · 90–95% batas beli</small></article><article><span>ALL IN biaya tinggi</span><strong>{{idr(selected.results.costHigh)}}</strong><small>{{selected.results.capitalPercent}}% dari modal per unit</small></article><article><span>Titik impas harga jual</span><strong>{{idr(selected.results.breakEvenSale)}}</strong><small>Harga jual untuk target laba: {{idr(selected.results.desiredSale)}}</small></article></div><p>ALL IN pada penawaran: {{idr(selected.results.costLow)}}–{{idr(selected.results.costHigh)}}. Selisih penawaran di atas batas beli: {{idr(selected.results.targetGap)}}. Admin {{idr(selected.fee_snapshot.adminFee)}} + {{selected.fee_snapshot.taxPercent}}% harga beli.</p>
<p>Harga jual input: {{idr(selected.data.saleLow)}} / {{idr(selected.data.saleMid)}} / {{idr(selected.data.saleHigh)}}. Servis {{idr(selected.data.repairLow)}}–{{idr(selected.data.repairHigh)}}; pajak kendaraan/dokumen {{idr(selected.data.taxCost)}}; biaya lain {{idr(selected.data.otherCosts)}}; cadangan {{idr(selected.data.riskBuffer)}}.</p><details><summary>Bukti harga & catatan dari user</summary><p class="decision-evidence">{{selected.data.marketEvidence||'Belum ada rincian pembanding'}}</p><p class="decision-evidence">{{selected.data.notes||'Belum ada catatan kondisi'}}</p><p>Harga ditandai terverifikasi: {{selected.data.evidenceConfirmed?'Ya':'Belum'}} · Inspeksi ditandai selesai: {{selected.data.inspectionConfirmed?'Ya':'Belum'}}.</p></details><div class="section-head"><h3>Simulasi harga beli & laba</h3></div><div class="table-wrap"><table><thead><tr><th>HARGA BELI</th><th>ALL IN RENDAH–TINGGI</th><th>LABA JUAL RENDAH</th><th>LABA JUAL TENGAH</th><th>LABA JUAL TINGGI</th><th>LABA KONSERVATIF</th><th>MODAL</th></tr></thead><tbody><tr v-for="s in selected.results.scenarios" :key="s.purchasePrice"><td><b>{{idr(s.purchasePrice)}}</b></td><td>{{idr(s.costLow)}}–{{idr(s.costHigh)}}</td><td>{{idr(s.profitAtLowSale)}}</td><td>{{idr(s.profitAtMidSale)}}</td><td>{{idr(s.profitAtHighSale)}}</td><td :class="s.downsideProfit<0?'red':'green'">{{idr(s.downsideProfit)}}</td><td>{{s.withinBudget?'Cukup':'Melebihi'}}</td></tr></tbody></table></div><p class="muted">Tiga kolom laba jual memakai biaya rendah. Laba konservatif memakai harga jual rendah + biaya tinggi. Cadangan risiko termasuk ALL IN; hitungan merupakan skenario, bukan keuntungan terjamin.</p>
<h3>Checklist sebelum beli</h3><ul><li v-for="c in selected.results.inspections" :key="c">{{c}}</li></ul><div v-if="photoUrls.length" class="decision-photos"><img v-for="p in photoUrls" :key="p.id" :src="p.url" alt="Foto unit dari user"></div>
<div class="section-head"><div><h3>Penjelasan & indikasi AI</h3><p>Opsional. Harga dan keputusan dihitung Java; AI membantu membaca indikasi dan menyusun alasan.</p></div><button class="secondary" :disabled="busy||!config.aiConfigured||selected.data.stnk!=='ADA'||selected.data.criticalRisk||selected.results.recommendation==='SKIP'||['QUEUED','PROCESSING'].includes(selected.ai_status)" @click="analyze"><Sparkles :size="16"/> {{selected.ai_status==='READY'?'Analisis AI ulang':'Analisis AI & foto'}}</button></div><div v-if="!config.aiConfigured" class="info-note">AI belum dikonfigurasi; simulasi perhitungan tetap tersedia.</div><p v-if="['QUEUED','PROCESSING'].includes(selected.ai_status)">AI sedang memproses. Status diperbarui otomatis.</p><div v-if="selected.ai_status==='FAILED'" class="error">{{selected.error}} · Perhitungan tersimpan tetap dapat digunakan.</div><template v-if="selected.ai"><p><b>{{selected.ai.summary}}</b></p><div class="decision-ai-grid"><section><h3>Pasar & target pembeli</h3><p>{{selected.ai.liquidity}}</p><p>{{selected.ai.buyerFit}}</p><h3>Strategi nego</h3><p>{{selected.ai.negotiationNotes}}</p></section><section v-for="[key,label] in [['observations','Indikasi yang terlihat'],['risks','Risiko'],['checks','Inspeksi prioritas'],['unknowns','Belum terverifikasi']]" :key="key"><h3>{{label}}</h3><p v-if="!selected.ai[key].length">Tidak ada indikasi tambahan yang dicatat.</p><ul><li v-for="s in selected.ai[key]" :key="s">{{s}}</li></ul></section></div><p class="muted">AI tanpa akses web. Indikasi pasar/kondisi tidak sama dengan riset transaksi atau inspeksi fisik. Model {{selected.usage.model}} · input {{selected.usage.inputTokens}} / output {{selected.usage.outputTokens}} token.</p></template>
<div class="heading-actions"><button class="secondary" @click="reset({...selected.data,evidenceConfirmed:false,inspectionConfirmed:false})">Ubah input / buat simulasi baru</button><button v-if="!selected.acquired_unit_id" class="primary" @click="purchase={price:selected.data.askPrice,date:new Date().toLocaleDateString('en-CA')}"><Car :size="16"/> Catat sudah dibeli</button><span v-else class="badge BID">Sudah dicatat di Unit dimenangkan</span></div><form v-if="purchase" class="decision-acquire" @submit.prevent="acquire"><p>Gunakan setelah transaksi selesai. Biaya estimasi tidak otomatis menjadi pengeluaran aktual.</p><div class="field-grid"><label>Harga beli aktual (Rp)<input v-model.number="purchase.price" type="number" min="1" max="100000000000" required></label><label>Tanggal beli<input v-model="purchase.date" type="date" required></label></div><div class="heading-actions"><button class="primary" :disabled="busy">Simpan pembelian aktual</button><button type="button" class="secondary" @click="purchase=null">Batal</button></div></form>
</section>
<section class="panel"><div class="section-head"><h3>Riwayat keputusan <span class="count">{{rows.length}}</span></h3></div><div v-if="!rows.length" class="empty"><Car :size="30"/><p>Isi unit dan parameter untuk mendapatkan laporan keputusan beli.</p></div><div class="table-wrap" v-else><table><thead><tr><th>UNIT / TANGGAL</th><th>PENAWARAN</th><th>BATAS BELI</th><th>KEPUTUSAN</th><th>AI</th><th/></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><b>{{r.data.vehicle}}</b><small>{{new Date(r.created_at).toLocaleString('id-ID')}}</small></td><td>{{idr(r.data.askPrice)}}</td><td>{{idr(r.results.maxPurchase)}}</td><td>{{labels[r.results.recommendation]}}</td><td>{{r.ai_status}}</td><td><button class="text-button" :disabled="busy" @click="perform(()=>load(r.id))">Buka keputusan</button></td></tr></tbody></table></div></section>
</template>
