package com.phivegarage;
import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.util.*;
import java.io.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
class DecisionTest {
 DecisionApi.Input input(long ask,long capital,long cap,String stnk,String bpkb,boolean evidence,boolean inspected,boolean risk){return new DecisionApi.Input("Synthetic sedan",2002,120000L,"AT",stnk,bpkb,ask,capital,cap,5_000_000,2_000_000,5_000_000,0,0,0,50_000_000,53_000_000,55_000_000,evidence,inspected,risk,"Synthetic notes","Synthetic price evidence","DIRECT",null,null);}
 DecisionCalculator.Report report(DecisionApi.Input d){return DecisionCalculator.calculate(d,0,BigDecimal.ZERO);}
 @Test void expensiveOfferNeedsNegoAndDownsideCanLoseMoney(){var r=report(input(48_000_000,65_000_000,50_000_000,"ADA","ADA",true,true,false));assertEquals("NEGOTIATE",r.recommendation());assertEquals(40_000_000,r.maxPurchase());assertEquals(36_000_000,r.negotiationLow());assertEquals(38_000_000,r.negotiationHigh());assertEquals(53_000_000,r.breakEvenSale());assertEquals(58_000_000,r.desiredSale());var s=r.scenarios().stream().filter(x->x.purchasePrice()==48_000_000).findFirst().orElseThrow();assertEquals(0,s.profitAtLowSale());assertEquals(3_000_000,s.profitAtMidSale());assertEquals(-3_000_000,s.downsideProfit());}
 @Test void missingEvidenceCannotBecomeBuy(){assertEquals("REVIEW",report(input(35_000_000,65_000_000,50_000_000,"ADA","ADA",false,true,false)).recommendation());assertEquals("REVIEW",report(input(35_000_000,65_000_000,50_000_000,"ADA","ADA",true,false,false)).recommendation());assertEquals("REVIEW",report(input(35_000_000,65_000_000,50_000_000,"ADA","UNKNOWN",true,true,false)).recommendation());}
 @Test void missingStnkOrCriticalRiskAlwaysBlocks(){assertEquals("SKIP",report(input(35_000_000,65_000_000,50_000_000,"UNKNOWN","ADA",true,true,false)).recommendation());assertEquals("SKIP",report(input(35_000_000,65_000_000,50_000_000,"ADA","ADA",true,true,true)).recommendation());}
 @Test void safeOfferCanBeConditionalBuyAndUserLimitIsHonored(){assertEquals("BUY_CONDITIONAL",report(input(35_000_000,65_000_000,50_000_000,"ADA","ADA",true,true,false)).recommendation());assertEquals(30_000_000,report(input(35_000_000,65_000_000,30_000_000,"ADA","ADA",true,true,false)).maxPurchase());}
 @Test void tinyCapitalLeavesNoFeasibleDeal(){var r=report(input(48_000_000,1_000_000,50_000_000,"ADA","ADA",true,true,false));assertEquals(0,r.maxPurchase());assertEquals("SKIP",r.recommendation());assertTrue(r.capitalPercent().compareTo(new BigDecimal("100"))>0);}
 @Test void auctionFeesAndRoundingRespectBudgetAndTarget(){var d=input(40_000_000,45_000_000,50_000_000,"ADA","ADA",true,true,false);var r=DecisionCalculator.calculate(d,3_000_000,new BigDecimal("1.1"));long a=r.maxPurchase()+BidCalculator.fee(r.maxPurchase(),3_000_000,new BigDecimal("1.1"))+d.repairHigh();assertTrue(a<=d.capital());assertTrue(d.saleLow()-a>=d.targetProfit());long next=r.maxPurchase()+1;assertTrue(next+BidCalculator.fee(next,3_000_000,new BigDecimal("1.1"))+d.repairHigh()>45_000_000);}
 @Test void corruptPhotoRejectedAndPngAccepted()throws Exception{assertThrows(IllegalArgumentException.class,()->DecisionJobs.photo(new byte[]{1,2,3}));try(var out=new ByteArrayOutputStream()){ImageIO.write(new BufferedImage(3,3,BufferedImage.TYPE_INT_RGB),"png",out);var p=DecisionJobs.photo(out.toByteArray());assertEquals("image/png",p.mime());assertEquals(".png",p.extension());}}
 @Test void aiMalformedOrNullFieldsCannotPass()throws Exception{var json=new ObjectMapper();assertThrows(IllegalStateException.class,()->DecisionJobs.validate(json.readTree("{}")));var node=json.readTree("{\"summary\":\"Indikatif\",\"liquidity\":\"Belum diketahui\",\"buyerFit\":\"Indikatif\",\"negotiationNotes\":\"Periksa\",\"observations\":[],\"risks\":[],\"checks\":[],\"unknowns\":[null]}");assertThrows(IllegalStateException.class,()->DecisionJobs.validate(node));}
 @Test void stnkGateStopsAiBeforeQueue(){var db=mock(JdbcTemplate.class);var json=new ObjectMapper();var store=spy(new Store(db,json));var ai=mock(AiClient.class);var jobs=mock(Jobs.class);var id=UUID.randomUUID();when(ai.enabled()).thenReturn(true);doReturn(Map.of("data",json.valueToTree(input(48_000_000,65_000_000,50_000_000,"UNKNOWN","ADA",true,true,false)))).when(store).one(anyString(),eq(id));var api=new DecisionApi(store,mock(AuctionHouses.class),jobs,ai,mock(DecisionJobs.class));assertThrows(IllegalArgumentException.class,()->api.analyze(id));doReturn(Map.of("data",json.valueToTree(input(48_000_000,1_000_000,50_000_000,"ADA","ADA",true,true,false)),"results",json.valueToTree(Map.of("recommendation","SKIP")))).when(store).one(anyString(),eq(id));assertThrows(IllegalArgumentException.class,()->api.analyze(id));verifyNoInteractions(db,jobs);}
 @Test void directSourceCannotSmuggleAuctionHouse(){var d=input(48_000_000,65_000_000,50_000_000,"ADA","ADA",true,true,false);assertDoesNotThrow(()->DecisionApi.validate(d));var bad=new DecisionApi.Input(d.vehicle(),d.year(),d.kilometer(),d.transmission(),d.stnk(),d.bpkb(),d.askPrice(),d.capital(),d.maxPurchase(),d.targetProfit(),d.repairLow(),d.repairHigh(),d.taxCost(),d.otherCosts(),d.riskBuffer(),d.saleLow(),d.saleMid(),d.saleHigh(),true,true,false,"","evidence","DIRECT",UUID.randomUUID(),null);assertThrows(IllegalArgumentException.class,()->DecisionApi.validate(bad));}

 @Test void badRangesAndUnsubstantiatedVerificationAreRejected(){var json=new ObjectMapper();var d=input(48_000_000,65_000_000,50_000_000,"ADA","ADA",true,true,false);var node=json.valueToTree(d);((com.fasterxml.jackson.databind.node.ObjectNode)node).put("repairLow",6_000_000);assertThrows(IllegalArgumentException.class,()->DecisionApi.validate(json.convertValue(node,DecisionApi.Input.class)));((com.fasterxml.jackson.databind.node.ObjectNode)node).put("repairLow",2_000_000).put("marketEvidence","");assertThrows(IllegalArgumentException.class,()->DecisionApi.validate(json.convertValue(node,DecisionApi.Input.class)));}
 @Test void directInventoryCanBeEditedWithoutCreatingAnAuctionHouse(){var db=mock(JdbcTemplate.class);var json=new ObjectMapper().findAndRegisterModules();var store=spy(new Store(db,json));var id=UUID.randomUUID();var row=new HashMap<String,Object>();row.put("auction_house_id",null);row.put("source_lot_id",null);doReturn(row).when(store).one(anyString(),eq(id));var api=new WonApi(store,mock(AuctionHouses.class),mock(Jobs.class),json);var d=new WonApi.UnitData("Synthetic sedan",2002,"",120000L,"",48_000_000L,40_000_000L,39_000_000L,java.time.LocalDate.of(2026,10,8),53_000_000L,53_000_000L,null,null,"","");assertDoesNotThrow(()->api.update(id,new WonApi.SaveUnit(null,null,d)));verify(db).update(eq("UPDATE won_units SET data=?::jsonb WHERE id=?"),anyString(),eq(id));}
}
